# Generated by Django 3.2.2 on 2021-06-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hasPassword',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='isAvailable',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Guest', max_length=16),
        ),
    ]
