# Generated by Django 3.2.2 on 2021-06-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toy_auth', '0001_initial'),
        ('omok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toy_auth.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
