# Generated by Django 3.2.2 on 2021-05-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
