# Generated by Django 3.2.2 on 2021-05-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0002_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=200)),
                ('isCompleted', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
