# Generated by Django 3.2.2 on 2021-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0004_alter_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='user_one',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='room',
            name='hasPassword',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='isAvailable',
            field=models.SmallIntegerField(default=1),
        ),
    ]
