# Generated by Django 3.2.2 on 2021-05-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0005_auto_20210526_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hasPassword',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
