# Generated by Django 3.2.2 on 2021-05-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0006_alter_room_haspassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
