# Generated by Django 3.2.2 on 2021-05-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0007_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('room_password', models.CharField(max_length=4, null=True)),
                ('isAvailable', models.SmallIntegerField(default=1)),
                ('hasPassword', models.SmallIntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omok.user')),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
