# Generated by Django 3.2.2 on 2021-05-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0008_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_password',
        ),
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
