# Generated by Django 3.2.2 on 2021-05-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0009_auto_20210529_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
    ]
