version: "3"

services: 
    db:
        image: mariadb
        restart : always
        env_file:
            -   ./.env
    redis:
        image: redis:alpine
        restart: always
        command : redis-server
        ports:
            - "6379:6379"
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        env_file:
            -   ./.env
        depends_on:
            - db
            - redis


