version: "3"

services: 
    db:
        image: mariadb
        restart : always
        env_file:
            -   ./.env
        volumes:
            - db-volumes:/var/lib/mariadb
    redis:
        image: redis:alpine
        restart: always
        command : ["redis-server", "--bind", "0.0.0.0"]
        ports:
            - "6379:6379"
        volumes:
            - redis-volumes:/data
        healthcheck:
            test: ["CMD", "redis-cli","-p 6379", "ping"]
            interval: 2s
            timeout: 1s
            retries: 10 
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - app-volumes:/data
        env_file:
            -   ./.env
        depends_on:
            - db
            - redis
volumes:
    db-volumes :
    redis-volumes:
    app-volumes :
            
