# Generated by Django 3.2.2 on 2021-06-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('isCompleted', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
