<<<<<<< HEAD:todolist/migrations/0001_initial.py
# Generated by Django 3.2.2 on 2021-06-02 01:40
=======
# Generated by Django 3.2.2 on 2021-05-23 02:53
>>>>>>> master:omok/migrations/0003_todo.py

from django.db import migrations, models


class Migration(migrations.Migration):

<<<<<<< HEAD:todolist/migrations/0001_initial.py
    initial = True

    dependencies = [
=======
    dependencies = [
        ('omok', '0002_delete_todo'),
>>>>>>> master:omok/migrations/0003_todo.py
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD:todolist/migrations/0001_initial.py
                ('text', models.CharField(max_length=200)),
=======
                ('todo_text', models.CharField(max_length=200)),
>>>>>>> master:omok/migrations/0003_todo.py
                ('isCompleted', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
