# Generated by Django 3.2.2 on 2021-06-22 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toy_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('toy_auth.user',),
        ),
        migrations.CreateModel(
            name='KakaoUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('toy_auth.user',),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_type']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_id',
        ),
        migrations.AddField(
            model_name='user',
            name='first_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Guest'), (1, 'Kakao')], default=0),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
