# Generated by Django 3.2.2 on 2021-06-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toy_auth', '0004_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
